[package]
name = "bosh_cli"
version = "0.0.0"

[[bin]]
name = "bosh"
path = "src/main.rs"

[dependencies]
compiler = { path = "../compiler" }

structopt = "0.1.0"
structopt-derive = "0.1.0"

serde_json = "1.0"
